Map<String, String> wordExplanations = {
  "Angry": "Feeling or showing strong displeasure and hostility.",
  "Answer": "A response to a question or problem.",
  "Apple": "A round, edible fruit with a red, green, or yellow skin.",
  "April": "The fourth month of the year.",
  "August": "The eighth month of the year.",
  "Bad": "Not good; of poor quality or low standard.",
  "Bag": "A container made of flexible material with an opening at the top.",
  "Bandage": "A strip of cloth used to bind a wound or injured part of the body.",
  "Bank": "A financial institution where people deposit or borrow money.",
  "Bathroom": "A room with a toilet and often a bath or shower.",
  "Beautiful": "Pleasing the senses or mind aesthetically.",
  "Best": "Of the highest quality, degree, or grade.",
  "Big": "Large in size, extent, or amount.",
  "Birthday": "The anniversary of the day on which someone was born.",
  "BodyPain": "Physical discomfort or suffering in the body.",
  "Bulb": "A rounded glass container with a filament inside that emits light when an electric current passes through it.",
  "Butter": "A dairy product made by churning cream.",
  "Bye": "A short way of saying goodbye.",
  "Calander": "A chart or table showing the days, weeks, and months of a year.",
  "Calculator": "An electronic device for performing mathematical calculations.",
  "Call": "To speak to someone on the phone.",
  "Calm": "Not showing or feeling nervousness, agitation, or excitement.",
  "Camel": "A desert animal with a humped back.",
  "Candle": "A cylindrical object made of wax with a wick that burns to produce light.",
  "Capsicum": "A bell pepper; a sweet pepper.",
  "Car": "A motor vehicle with four wheels.",
  "Carrot": "A long, orange root vegetable.",
  "Cat": "A small, furry mammal often kept as a pet.",
  "Chair": "A seat with a back and four legs.",
  "Change": "To make or become different.",
  "Cheap": "Low in price; not expensive.",
  "Chocolate": "A sweet food made from cacao beans.",
  "Class": "A group of students taught together.",
  "Clock": "A device for measuring and displaying time.",
  "Coconut": "A large, brown fruit with a hard shell and white flesh.",
  "Cold": "Having a low temperature.",
  "Colour": "The visual sensation produced by the light waves of certain wavelengths.",
  "Computer": "An electronic device for storing and processing data.",
  "Correct": "Free from error; accurate.",
  "Cost": "The amount that something costs.",
  "Cow": "A large female mammal that produces milk.",
  "Curd": "The thick, solid part of milk that has coagulated.",
  "Cute": "Attractive in a pretty or charming way.",
  "Cycle": "A bicycle.",
  "Dance": "To move rhythmically to music.",
  "Dark": "With little or no light.",
  "Daughter": "A female child.",
  "December": "The twelfth month of the year.",
  "Demand": "An insistent request.",
  "Dentist": "A person who treats people's teeth.",
  "Dinner": "The main meal of the day, typically eaten in the evening.",
  "Discipline": "The practice of training oneself to obey rules or a code of behavior.",
  "Disrespect": "Lack of respect or reverence.",
  "Dog": "A domesticated carnivorous mammal.",
  "Donkey": "A domesticated animal of the horse family.",
  "Doubt": "A feeling of uncertainty or disbelief.",
  "Dress": "A garment worn by women or girls.",
  "Eagle": "A large bird of prey with a powerful beak and keen eyesight.",
  "Easy": "Achieved without great effort; not difficult.",
  "Egg": "A oval or round object laid by a female bird, reptile, or fish.",
  "Electricity": "A form of energy caused by the movement of electrons.",
  "Elephant": "A large mammal with a trunk and tusks.",
  "Emergency": "A serious, unexpected, and often dangerous situation requiring immediate action.",
  "Evening": "The period of time at the end of the day.",
  "Family": "A group of people related by blood, marriage, or adoption.",
  "Fast": "Moving or capable of moving at high speed.",
  "Father": "A male parent.",
  "Favourite": "Liked best; preferred above all others.",
  "Fear": "An unpleasant emotion caused by the perception of danger, pain, or threat.",
  "February": "The second month of the year.",
  "Female": "Relating to women or girls.",
  "Find": "To discover or locate something unexpectedly or while looking for something else.",
  "Finish": "To bring something to an end; complete.",
  "Fire": "Combustion or burning.",
  "Fish": "A limbless vertebrate animal with gills and fins that lives in water.",
  "Forget": "To fail to remember.",
  "Forgive": "To stop feeling angry or resentful toward someone for an offense.",
  "Friday": "The sixth day of the week.",
  "Friend": "A person whom one knows and with whom one has a bond of mutual affection.",
  "Games": "Activities engaged in for pleasure.",
  "Gift": "Something given willingly to someone.",
  "Girl": "A female child or young woman.",
  "Give": "To transfer the possession of something to someone else.",
  "Go": "To move from one place to another.",
  "God": "The name of the creator of the universe.",
  "GoodMorning": "A greeting used when meeting someone in the morning.",
  "GoodNight": "A farewell said in the evening or before going to bed.",
  "Government": "The governing body of a nation, state, or community.",
  "Granddaughter": "The daughter of one's son or daughter.",
  "Grandfather": "The father of one's parent.",
  "Grandmother": "The mother of one's parent.",
  "Grandson": "The son of one's son or daughter.",
  "Happy": "Feeling or showing pleasure or contentment.",
  "He": "A pronoun used to refer to a male person or animal previously mentioned or easily identified.",
  "Holiday": "A day of celebration or rest from work.",
  "IceCream": "A frozen dessert made from milk or cream.",
  "India": "A country in South Asia.",
  "January": "The first month of the year.",
  "Jealous": "Feeling or showing envy of someone or their achievements and attributes.",
  "July": "The seventh month of the year.",
  "June": "The sixth month of the year.",
  "Kitchen": "A room or area where food is prepared and cooked.",
  "Knife": "A cutting instrument with a blade and a handle.",
  "Know": "To be aware of through observation, inquiry, or information.",
  "Life": "The condition that distinguishes animals and plants from inorganic matter.",
  "Light": "The natural agent that stimulates sight and makes things visible.",
  "Like": "To enjoy or be pleased with.",
  "Lock": "A mechanism for fastening something closed.",
  "Love": "An intense feeling of deep affection.",
  "Lunch": "A meal eaten in the middle of the day.",
  "Man": "An adult male human being.",
  "Mango": "A tropical fruit with sweet, juicy flesh.",
  "March": "The third month of the year.",
  "Market": "A place where goods are bought and sold.",
  "May": "The fifth month of the year.",
  "Mistake": "An act or judgment that is misguided or wrong.",
  "Monday": "The first day of the week.",
  "Money": "A medium of exchange.",
  "Mother": "A female parent.",
  "My": "Used by a speaker to refer to something that belongs to them.",
  "Myself": "Used by a speaker to refer to themselves as the subject of a verb.",
  "Namaste": "A respectful greeting or salutation said when meeting or leaving someone.",
  "Name": "A word or set of words by which a person, animal, place, or thing is known.",
  "Neighbour": "A person living next door or near by.",
  "Never": "At no time; not ever.",
  "Nice": "Pleasant or agreeable.",
  "No": "Used to give a negative response.",
  "November": "The eleventh month of the year.",
  "Nurse": "A person trained to care for the sick or injured.",
  "October": "The tenth month of the year.",
  "Okay": "All right; satisfactory.",
  "Open": "Not closed or locked.",
  "Opinion": "A view or judgment formed about something, not necessarily based on fact or knowledge.",
  "Pain": "Physical suffering or discomfort caused by illness or injury.",
  "Paper": "A thin material made from wood pulp, used for writing, printing, or wrapping.",
  "Parents": "A father or mother.",
  "Pen": "An instrument for writing or drawing with ink.",
  "Pencil": "A writing instrument with a graphite core.",
  "People": "Human beings in general or considered collectively.",
  "Pizza": "A flat, round bread base topped with tomato sauce, cheese, and various toppings.",
  "Plate": "A shallow, usually circular dish used for eating from.",
  "Play": "To engage in activity for enjoyment and recreation.",
  "Please": "Used to make a polite request.",
  "Police": "A civil force responsible for the prevention and detection of crime and the maintenance of public order.",
  "Polite": "Having or showing behavior that is respectful and considerate of other people.",
  "Principal": "The head of a school.",
  "Private": "Belonging to, or for the use of, an individual person or group; not public.",
  "Qualification": "A condition or standard that must be complied with.",
  "Question": "A sentence worded so as to elicit information.",
  "Rasgula": "A syrupy dessert popular in India.",
  "Rat": "A rodent that is similar to a mouse but larger.",
  "Reason": "A cause, explanation, or justification for an action or event.",
  "Request": "An act of asking politely and formally for something.",
  "Rest": "Cease work or movement in order to relax, refresh oneself, or recover strength.",
  "Rice": "A cereal grain that is the most widely consumed staple food.",
  "Rude": "Offensively impolite or discourteous.",
  "Sad": "Feeling or showing sorrow; unhappy.",
  "Safe": "Protected from danger or risk.",
  "Salt": "A white crystalline substance, sodium chloride, used for seasoning food.",
  "Salwar": "A type of South Asian garment.",
  "Samosa": "A savory pastry filled with spiced potatoes, peas, or other ingredients.",
  "Sandwich": "Two or more slices of bread with a filling between them.",
  "SanitaryPad": "An absorbent item worn by women during their menstrual period.",
  "Saturday": "The seventh day of the week.",
  "School": "An institution for educating children.",
  "Self": "A person's own being or individuality.",
  "Shirt": "A garment worn on the upper body.",
  "Sleep": "A condition of body and mind rest typically lasting several hours.",
  "Son": "A male child.",
  "Spoon": "A utensil consisting of a small shallow bowl with a handle.",
  "Stop": "Bring or come to an end.",
  "Student": "A person who is studying at a school or college.",
  "Sunday": "The first day of the week.",
  "Taxi": "A vehicle licensed to transport passengers for a fee.",
  "Tea": "A hot drink made by infusing the dried leaves of the tea plant in hot water.",
  "Teacher": "A person who teaches, especially in a school.",
  "Team": "A group of people who play or work together.",
  "ThankYou": "An expression of gratitude.",
  "Thristy": "Feeling or showing a need to drink.",
  "Thursday": "The fifth day of the week.",
  "Tie": "A long piece of cloth worn around the neck by men.",
  "Today": "This present day.",
  "Tomorrow": "The day after today.",
  "Toothbrush": "A brush with a long handle used for cleaning the teeth.",
  "Trust": "Firm belief in the reliability, truth, or ability of someone or something.",
  "Tuesday": "The third day of the week.",
  "Umbrella": "A portable canopy used to shield oneself from rain or sun.",
  "Uncle": "The brother of one's father or mother, or the husband of one's aunt.",
  "Uncomfortable": "Causing or feeling physical discomfort.",
  "Vegetables": "A plant or part of a plant used as food.",
  "Village": "A small community in a rural area.",
  "Vomiting": "To eject matter from the stomach through the mouth.",
  "Wait": "Remain in one place or position until something expected happens.",
  "WakeUp": "To stop sleeping.",
  "Walk": "Move at a regular pace by lifting and setting down each foot in turn.",
  "Wallet": "A small leather or fabric pouch for carrying money and cards.",
  "Washroom": "A room with a toilet and often a sink.",
  "Water": "A colorless, transparent, odorless liquid that forms the seas, lakes, rivers, and rain.",
  "We": "Used by a speaker to refer to himself or herself and one or more other people.",
  "Weak": "Lacking the power to perform physically demanding tasks.",
  "Wedding": "A marriage ceremony and the celebrations associated with it.",
  "Wednesday": "The fourth day of the week.",
  "Wet": "Covered or soaked with liquid.",
  "What": "Used to ask for information about something.",
  "Where": "In or at what place or position.",
  "Which": "Used to ask for information specifying one or more people or things from a definite set.",
  "Wife": "The woman to whom a man is married.",
  "Window": "An opening in a wall or roof that admits light and air.",
  "Woman": "An adult female human being.",
  "Work": "Activity involving mental or physical effort done in order to achieve a purpose.",
  "Wound": "An injury, typically one in which the skin is cut or broken.",
  "Write": "Mark (letters, words, or symbols) on a surface.",
  "Wrong": "Not correct or true; incorrect.",
  "Yes": "Used to express affirmation or agreement.",
  "Yesterday": "The day before today.",
  "YoungerBrother": "A male sibling younger than oneself.",
  "YoungerSister": "A female sibling younger than oneself.",
};